[phases.setup]
nixPkgs = ["python313", "ffmpeg", "fontconfig", "dejavu_fonts", "liberation_ttf"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "fc-cache -fv"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
